use working method

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -92,9 +92,15 @@ runs:
         version=""
 
         if [[ "${action_ref}" =~ ^[0-9a-f]{40}$ ]]; then
-          version=$(gh api -H "Accept: application/vnd.github+json" \
+          version="$(gh api -H "Accept: application/vnd.github+json" \
                             -H "X-GitHub-Api-Version: 2022-11-28" \
-                            "/repos/${action_repository}/git/tags/${action_ref}" | jq -r '.tag')
+                            /repos/${action_repository}/git/refs/tags \
+                            | jq --raw-output --arg sha "${action_ref}" \
+                                '[.[] | select(.object.sha == $sha) | .ref | split("/")[-1]][-1] // ""')"
+          if [[ -z "${version}" ]]; then
+            echo "Could not find a tag with the digest ${action_ref}" >&2
+            exit 1
+          fi
         elif [[ "${action_ref}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
           version="${action_ref}"
         fi
